
- name: create zookeeper group
  group:
    name: zookeeper
    state: present

- name: create zookeeper user
  user: 
    name: "{{ storm }}"
    password:  " {{ storm | password_hash('sha512') }}"
    group: sudo
    state: present

- name: download zookeeper tar
  get_url:
    url: "https://mirrors.estointernet.in/apache/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: /root/zookeeper.tar.gz
    owner: "{{ storm }}"



- name: Untar zookeeper 
  unarchive:
    src: /root/zookeeper.tar.gz
    dest: /etc/
    owner: "{{ storm }}"
    remote_src: yes
  

- name: configure and change conf file
  copy:
    src: zoo.cfg
    dest: "/etc/apache-zookeeper-{{ zookeeper_version }}-bin/conf/zoo.cfg"
    owner: "{{ storm }}"
    group: zookeeper

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ storm }}"
    group: zookeeper
  with_items:
    - /zookeeper
    - /zookeeper/logs


- name: Copy ZK service file
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service

- name: Add nimbus and ui  service files
  template:
    src: "services.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: storm
    group: storm
  with_items:
    - nimbus
    - ui

    

- name: start all services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - zookeeper
    - nimbus
    - ui

    