
- name: create zookeeper group
  group:
    name: zookeeper
    state: present

- name: create zookeeper user
  user: 
    name: storm
    password:  " {{ storm | password_hash('sha512') }}"
    group: sudo
    state: present

- name: download zookeeper tar
  get_url:
    url: http://www.gtlib.gatech.edu/pub/apache/zookeeper/stable/zookeeper-3.4.6.tar.gz
    dest: /root/
    owner: "{{ storm }}"

- name: Untar zookeeper 
  unarchive:
    src: /root/zookeeper-3.4.6.tar.gz
    dest: /root/
    owner: "{{ storm }}"
- name: copy contents
  copy:
    src: /root/zookeeper-3.4.6
    dest: /etc/zookeeper/
    owner: zookeeper

- name: configure and change conf file
  copy:
    src: zoo.conf
    dest: /etc/zookeeper/conf/zoo.cfg
    owner: "{{ storm }}"
    group: zookeeper

- name: Start zookeeper service
  service:
    name: zookeeper
    state: started
    enabled: yes

- name: Add service files
  copy:
    src: nimbus 
    dest: /etc/init/nimbus.conf

- name: Add  for ui file
  copy:
    src:  ui
    dest: /etc/init/ui.conf

- name: start all services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nimbus
    - ui

    