- hosts: localhost
  vars_files:
    - "keypair.yml"
  vars_prompt:
    - name: worker
      prompt: "How many worker nodes"
      private: no
    
  tasks:
    - name: Launch AWS instances
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: yes
        group: "{{ group }}"
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
      register: ec2

    - name: Create ssh group to login dynamically to EC2 Instance
      add_host: 
        hostname: "{{ item.public_ip }}"
        groupname: ec2_server
      with_items: ec2.instances

    - name: Wait for ssh to come up
      wait_for: 
        host: "{{ item.public_ip }}" 
        port: 22 
        state: started
      with_items: ec2.instances

- hosts: ec2_server
  become: yes
  remote_user: ubuntu 
  gather_facts: yes
  roles:
    - webserver
