- hosts: localhost
  vars_files:
    - "key.yml"
  vars_prompt:
    - name: worker
      prompt: "How many worker nodes"
      private: no
    
  tasks:
    - name: Launch AWS nimbus node
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: yes
        group: "{{ group }}"
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
      register: ec2_nimbus
    
    - name: Launch AWS supervisior nodes
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: yes
        group: "{{ group }}"
        count: "{{ worker }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
      register: ec2
    
    - name: create hosts file 
      template:
        src: hostsnew
        dest: hostsend
      with_items:
        - "{{ ec2_nimbus.instances }}"
        - "{{ ec2.instances }}"

    - name: Create ssh group to login dynamically to EC2 Instance nimbus nodes
      add_host: 
        hostname: "{{ item.public_ip }}"
        groupname: nimbus
      with_items:
        - "{{ ec2_nimbus.instances }}"
        - "{{ ec2.instances }}"
    
    
    - name: add aws ips 
      template:
        src: hostsnew
        dest: hostsfile
      with_items: 
        - "{{ ec2.instances }}"
        - "{{ ec2_nimbus.instances }}"

    - name: Wait for ssh to come up
      wait_for: 
        host: "{{ item.public_ip }}" 
        port: 22 
        state: started
        with_items: 
          - "{{ ec2.instances }}"
          - "{{ ec2_nimbus.instances }}"

- hosts: nimbus
  vars:
    ansible_python_interpreter: /usr/bin/python3
  remote_user: ubuntu
  connection: ssh
  become: yes
  gather_facts: no
  
  tasks:
    - copy:
        src: hostnew
        dest: /etc/hosts 
    - include_role: 
        name: "{{ item }}"
      with_items:
        - storm
        - zookeeper

- hosts: workernodes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  remote_user: ubuntu
  connection: ssh
  become: yes
  gather_facts: no
  
  tasks:
  - copy:
      src: hostsfile
      dest: /etc/hosts 
  - include_role:
      name: storm
  - copy:
      src: supervisior.conf
      dest: /etc/init/supervisor.conf
  - service:
      name: supervisior
      state: started
    


