- name: remove cdrom lines
  lineinfile:
    path: /etc/apt/sources.list
    regexp: "cdrom(.*)$"
    line: " "

- name: remove binary
  command: "apt-get update -y"




- name: Install packages
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
    force: yes
  
  