- name: create storm group
  group:
    name: storm
    state: present

- name: create storm user
  user: 
    name: storm
    password:  " {{ storm | password_hash('sha512') }}"
    group: storm
    state: present

- name: download apache storm tar
  get_url:
    url: http://apachemirror.wuchna.com/storm/apache-storm-2.1.0/apache-storm-2.1.0.tar.gz
    dest: /root/storm.tar.gz

- name: Untar apache storm
  unarchive:
    src: /root/storm.tar.gz
    dest: /usr/share/
    remote_src: yes

- name: permissions setup
  file:
    dest: /usr/share/apache-storm-2.1.0
    owner: storm
    group: storm
    recurse: yes

- name: Create log directories
  file:
    dest: /var/log/storm/workers-artifacts/
    owner: storm
    group: storm
    recurse: yes

- name: copy config file
  copy:
    src: storm.yaml
    dest: /usr/share/apache-storm-2.1.0/conf/storm.yaml
    owner: storm
    group: storm


- name: linking
  file:
    src: "/usr/share/apache-storm-2.1.0/bin/storm"
    dest: /usr/bin/storm
    owner: storm
    group: storm
    state: link

- name: Create Directory
  file:
    path: /var/storm
    state: directory
    owner: storm
    group: storm
