- name: create zookeeper group
  group:
    name: storm
    state: present

- name: create zookeeper user
  user: 
    name: storm
    password:  " {{ storm | password_hash('sha512') }}"
    group: sudo
    state: present

- name: download apache storm tar
  get_url:
    url: http://apachemirror.wuchna.com/storm/apache-storm-2.1.0/apache-storm-2.1.0.tar.gz
    dest: /root/storm.tar.gz

- name: Untar apache storm
  unarchive:
    src: /root/storm.tar.gz
    dest: /usr/share/
    owner: storm
    group: storm
    remote_src: yes

- name: copy config file
  copy:
    src: storm.yaml
    dest: /usr/share/apache-storm-2.1.0/conf/storm.yaml


- name: linking
  file:
    src: "/usr/share/apache-storm-2.1.0/bin/storm"
    dest: /usr/bin/storm
    owner: storm
    group: storm
    state: link
