- name: create storm group
  group:
    name: storm
    state: present

- name: create storm user
  user: 
    name: storm
    password:  " {{ storm | password_hash('sha512') }}"
    group: storm
    state: present

- name: download apache storm tar
  get_url:
    url: "http://apachemirror.wuchna.com/storm/apache-storm-{{ storm_version }}/apache-storm-{{ storm_version }}.tar.gz"
    dest: /root/storm.tar.gz

- name: Untar apache storm
  unarchive:
    src: /root/storm.tar.gz
    dest: /usr/share/
    remote_src: yes

- name: permissions setup
  file:
    dest: "/usr/share/apache-storm-{{ storm_version }}"
    owner: storm
    group: storm
    recurse: yes

- name: Create log directories
  file:
    dest: /var/log/storm/workers-artifacts/
    owner: storm
    group: storm
    recurse: yes

- name: copy config file
  copy:
    src: storm.yaml
    dest: "/usr/share/apache-storm-{{ storm_version }}/conf/storm.yaml"
    owner: storm
    group: storm


- name: linking
  file:
    src: "/usr/share/apache-storm-{{ storm_version }}/bin/storm"
    dest: /usr/bin/storm
    owner: storm
    group: storm
    state: link

- name: Create Directory
  file:
    path: /var/storm
    state: directory
    owner: storm
    group: storm


- name: Enable Log Viewer
  template:
    src: "services.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: storm
    group: storm
  with_items:
    - logviewer

- name: Start service
  service:
    name: logviewer
    state: started

